env:
  HADOOP_OPTS: -Phadoop-2.2 -Dhadoop.version=2.2.0
  SCALA_OPTS: -Dscala-2.11
  MAVEN_PROFILES: -Pyarn -Pnetlib-lgpl
  MAVEN_OPTS: $HADOOP_OPTS $MAVEN_PROFILES $SCALA_OPTS -DskipTests=true
  SKIP_VERSION_OVERRIDE: 1

steps:
  - description: "Compile source and pacakge"
    commands:
      - mvn $MAVEN_ARGS
            clean
            package
  - description: "Create distribution"
    commands:
      - ./dev/make-distribution.sh --name hubspot-spark-2.0.0-scala-211 --tgz $HAOOP_OPTS $MAVEN_PROFILES $SCALA_OPTS
